import type { Metadata } from "next";
import "../globals.css";
import { iranSans, teko } from "../ui/font";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "../../i18n/routing";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html
      dir={locale === "en" ? "ltr" : "rtl"}
      lang={locale}
      className={`${iranSans.variable} ${teko.variable}`}
    >
      <body
        className={`${
          locale === "en" ? "font-teko text-2xl" : "font-iranSans"
        } antialiased overflow-hidden`}
      >
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
